Repository mtavares1221/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#4 Integrar Arquitetura v1.0
  docs/arquitetura.md
Labels: arquitetura

#6 Integrar Implementação v1.0
  src/jogovelha.py
Labels: programação

#8 Integrar testes v1.0
  src/teste_inic.py
  src/testes_jogar.py
Labels: testes

#9 Gerar release v1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/teste_inic.py
  src/testes_jogar.py
Labels: operações

#11 Integrar Requisitos v1.1
  docs/requisitos.md
Labels: análise

#15 Integrar implementacao v1.1
  src/jogovelha.py
Labels: programação

#17 integrar testes v1.1
  src/teste_inic.py
  src/testes_jogar.py
Labels: testes

#18 Gerar release v1.1
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/teste_inic.py
  src/testes_jogar.py
Labels: operações
